apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-js-app
  labels:
    app: sample-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-js-app
  template:
    metadata:
      labels:
        app: sample-js-app
    spec:
      containers:
      - name: sample-js-app
        image: DOCKERHUB_USERNAME/sample-js-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: "sample-js-app"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
